Table "actions_users" {
  "fech" datetime [pk, not null, note: 'En minutos 00 y segundos 00']
  "session_id" int [not null, default: 0, note: 'Durante que sesion el usuario realizo esta acción']
  "action" varchar(50) [not null, note: 'Qué acción hizo']
}

Table "session_users" {
  "id" int [pk, not null]
  "fech" varchar(40) [not null, note: 'rfc + fecha DD-MM-YY_HH-MM-SS']
  "rfc" varchar(13) [unique, not null, note: 'RFC del usuario que accedio al sistema']
  "fech_con" datetime [not null, note: 'Fecha y hora de conexión']
  "fech_discon" datetime [note: 'Fecha y hora de desconexión']
}

Table "usuarios" {
  "rfc" varchar(50) [pk, not null]
  "email" varchar(50) [unique, not null]
  "username" varchar(50) [unique, not null]
  "password" varchar(255)
  "rol" int [note: '# 0 == Cliente, 1 == Capturista, 2 == Técnico, 3 == Administrador, 4 = Compañia']
  "last_session" datetime
  "fech_created" datetime [default: `now()`]
  "imagen" varchar(255)
  "id_company" varchar(13)
}

Table "visitas" {
  "id" int [pk, not null, note: 'Identificador único de la visita']
  "url" int [not null]
  "ip_user" varchar(255) [not null, note: 'Nombre del tipo de informe (Ejemplo: Tráfico, Conversión)']
  "user_agent" text [note: 'Información del navegador y dispositivo del usuario']
  "tiempo_carga" text [not null]
  "rfc_user" varchar(13)
  "origin" text [not null]
  "fecha_int" text [not null]
  "fecha_out" text
  "is_rebote" tinyint(1) [default: 0]
}

Ref "FK_action":"session_users"."id" < "actions_users"."session_id"

Ref "FK_26712":"usuarios"."rfc" < "session_users"."rfc"

Ref "FK_user_8712":"usuarios"."rfc" < "visitas"."rfc_user"
